server:
  port: 8082

#线程池配置参数
task:
  pool:
    corePoolSize: 5 #设置核心线程数
    maxPoolSize: 20  #设置最大线程数
    keepAliveSeconds: 300 #设置线程活跃时间（秒）
    queueCapacity: 50 #设置队列容量

# 监控相关配置
# 开启监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
