server:
  port: 8082

#线程池配置参数
task:
  pool:
    corePoolSize: 5 #设置核心线程数
    maxPoolSize: 20  #设置最大线程数
    keepAliveSeconds: 300 #设置线程活跃时间（秒）
    queueCapacity: 50 #设置队列容量

# redis相关配置
spring:
  redis:
    host: 139.224.103.236
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 10000
    # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 0
    # 连接池最大连接数（使用负值表示没有限制） 默认 8
    lettuce.pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
      max-wait: -1
      # 连接池中的最大空闲连接 默认 8
      max-idle: 8
      # 连接池中的最小空闲连接 默认 0
      min-idle: 0
    #集群
    #cluster.nodes: IP:7001

  redisson:
    address: "redis://139.224.103.236:6379"


# 监控相关配置
# 开启监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
