server:
  port: 8080
#spring:
#  profiles:
#    active: prod
---
server:
  port: 8081
spring:
  profiles: dev

---
server:
  port: 8082
spring:
  profiles: prod

#person:
#  name: "江峰"
#  age: 3
#  arr: [1, 2, 3]
#  car:
#    name: "兰博基尼"