spring:
#  配置数据源
  datasource:
    url: jdbc:mysql://localhost:3306/jpa
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    username: root

#  配置jpa
  jpa:
#    控制台上显式SQL
    show-sql: true
#    更新或者创建表结构
    hibernate:
      ddl-auto: update