server:
  port: ${port:8081}

# 暴露监控
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  metrics:
    export:
      datadog:
        application-key: ${spring.application.name}
spring:
  application:
    name: test-ms
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
        cluster-name: DEFAULT
