server:
  port: 8080

#线程池配置参数
task:
  pool:
    corePoolSize: 10 #设置核心线程数
    maxPoolSize: 20  #设置最大线程数
    keepAliveSeconds: 300 #设置线程活跃时间（秒）
    queueCapacity: 50 #设置队列容量

# redis相关配置
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 10000
    # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 0
    # 连接池最大连接数（使用负值表示没有限制） 默认 8
    lettuce.pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
      max-wait: -1
      # 连接池中的最大空闲连接 默认 8
      max-idle: 8
      # 连接池中的最小空闲连接 默认 0
      min-idle: 0
    #集群
    #cluster.nodes: IP:7001
  redisson:
    address: "redis://127.0.0.1:6379"

  profiles:
    active: dev

  # 服务名字
  application:
    name: template-ms

  # 注册到nacos里面
  cloud:
    nacos:
      discovery:
        namespace: dev
        server-addr: 139.224.103.236:8848


# RocketMQ
rocketmq:
  name-server: 139.224.103.236:9876
  producer:
    group: template-ms

# 监控相关配置
# 开启监控
management:
  endpoints:
    web:
      exposure:
        include: "*"



# 开启feign客户端对hystrix的支持。不然feign里面对于hystrix的操作不会生效。
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # hystrix的超时时间

#ribbon的超时时间
ribbon:
  ReadTimeout: 1000
  ConnectTimeout: 3000
  MaxAutoRetries: 2 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试


## 日志配置
logging:
  config: classpath:logback-spring.xml