server:
  port: 8083

# 监控相关配置
# 开启监控
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
        namespace: dev
        server-addr: 127.0.0.1:8848


# 开启feign客户端对hystrix的支持。不然feign里面对于hystrix的操作不会生效。
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # hystrix的超时时间

#ribbon的超时时间
ribbon:
  ReadTimeout: 1000
  ConnectTimeout: 3000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 2 #重试负载均衡其他的机器实例个数（不包括首次调用的机器，为1时，包括本机器，超时时，共有两个机器会接受到请求）
  OkToRetryOnAllOperations: false  #是否所有操作都重试
